apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-application
  labels:
    app: tech-fiap-application
spec:
  replicas: 5
  selector:
    matchLabels:
      app: tech-fiap-application
  template:
    metadata:
      labels:
        app: tech-fiap-application
    spec:
      containers:
        - name: tech-fiap-api-container
          image: 968379224811.dkr.ecr.us-east-1.amazonaws.com/fiap_fast_food_app
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-api
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
               secretKeyRef:
                  name: secret-api
                  key: DB_PASSWORD
          envFrom:
            - configMapRef:
                name: cm-api
          ports:
            - containerPort: 8080
