apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-fiapfastfoodapp
  labels:
    app: fiapfastfoodapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fiapfastfoodapp
  template:
    metadata:
      labels:
        app: fiapfastfoodapp
    spec:
      containers:
        - name: fiapfastfoodapp
          image: <account_id>.dkr.ecr.us-east-1.amazonaws.com/fiap_fast_food_app:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-api
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
               secretKeyRef:
                  name: secret-api
                  key: DB_PASSWORD
          envFrom:
            - configMapRef:
                name: cm-api
          ports:
            - containerPort: 8080
