name: Deploy to ECR

on:
 
  push:
    branches: [ main ]

env:
  ECR_REPOSITORY: rds-fiap
  EKS_CLUSTER_NAME: rds-tech-challenge 
  AWS_REGION: us-east-2

jobs:
  
  build:
    
    name: Deployment
    runs-on: ubuntu-latest

    steps:

    - name: Set short git commit SHA
      id: commit
      uses: prompt/actions-commit-hash@v2

    - name: Check out code
      uses: actions/checkout@v2

    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.30.2' # default is latest stable
      id: install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{env.AWS_REGION}}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Update kube config
      run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

    - name: Deploy to EKS
      run: |
        aws sts get-caller-identity
        kubectl apply --validate=false -f infra/cm/cm_db.yaml
        kubectl apply -f infra/pv/pv_db.yaml        
        kubectl apply -f infra/pvc/pvc_db.yaml
        kubectl apply -f infra/secrets/secret_db.yaml
        kubectl apply -f infra/sts/sts_db.yaml
        kubectl apply -f infra/svc/svc_db.yaml                        

